### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by Lmmb74** [Simonsator/Poke-for-Party-and-Friends#1]
https://github.com/Simonsator/Poke-for-Party-and-Friends/blob/2decf009b78036d052046f971c59d0dd5bf38d67/src/main/resources/plugin.yml#L6

Despite the fact that this file is more than a year old, I considered that it would be nice to report it.

**Comment by Simonsator** [comment]
Fixed with https://github.com/Simonsator/Poke-for-Party-and-Friends/commit/6d95c7e031ce0d01bf09b04c61722b6ae99c85bb
